// Professional Theme Presets - Telegram & WhatsApp Inspired
// Complete themes with both background + bubble colors preset together

import type { ChatTheme } from '../store/chatSettingsStore';

export interface ThemePreset {
  id: string;
  name: string;
  category: 'featured' | 'solid' | 'gradient' | 'pattern' | 'artistic';
  description: string;
  theme: ChatTheme;
}

export const themePresets: ThemePreset[] = [
  // ============ FEATURED THEMES (Standalone premium themes with custom backgrounds) ============
  {
    id: 'featured-tech-purple',
    name: 'Tech Purple',
    category: 'featured',
    description: 'Purple-pink tech pattern',
    theme: {
      backgroundType: 'featured',
      backgroundColor: '#0a0a0a',
      backgroundImage: '/src/assets/chat_themes/tech-1-theme.png',
      sentBubbleColor: '#a855f7',
      receivedBubbleColor: '#1e1b4b',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'purple',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e0e7ff',
    },
  },
  {
    id: 'featured-equations-rainbow',
    name: 'Math Rainbow',
    category: 'featured',
    description: 'Colorful physics equations',
    theme: {
      backgroundType: 'featured',
      backgroundColor: '#0a0a0a',
      backgroundImage: '/src/assets/chat_themes/equations-1-theme.png',
      sentBubbleColor: '#f59e0b',
      receivedBubbleColor: '#7c3aed',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'orange',
      sentTextColor: '#ffffff',
      receivedTextColor: '#f3e8ff',
    },
  },
  {
    id: 'featured-productivity-gold',
    name: 'Productivity',
    category: 'featured',
    description: 'Golden productivity theme',
    theme: {
      backgroundType: 'featured',
      backgroundColor: '#0a0a0a',
      backgroundImage: '/src/assets/chat_themes/productivity-theme.png',
      sentBubbleColor: '#f59e0b',
      receivedBubbleColor: '#78350f',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'orange',
      sentTextColor: '#ffffff',
      receivedTextColor: '#fef3c7',
    },
  },
  {
    id: 'featured-space-explorer',
    name: 'Space Explorer',
    category: 'featured',
    description: 'Orange-purple space',
    theme: {
      backgroundType: 'featured',
      backgroundColor: '#0a0a0a',
      backgroundImage: '/src/assets/chat_themes/space-theme.png',
      sentBubbleColor: '#f97316',
      receivedBubbleColor: '#6b21a8',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'orange',
      sentTextColor: '#ffffff',
      receivedTextColor: '#f3e8ff',
    },
  },
  {
    id: 'featured-hardware-split',
    name: 'Hardware',
    category: 'featured',
    description: 'Blue-orange hardware',
    theme: {
      backgroundType: 'featured',
      backgroundColor: '#0a0a0a',
      backgroundImage: '/src/assets/chat_themes/hardware-theme.png',
      sentBubbleColor: '#f97316',
      receivedBubbleColor: '#1e40af',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'orange',
      sentTextColor: '#ffffff',
      receivedTextColor: '#dbeafe',
    },
  },
  {
    id: 'featured-sports-vibrant',
    name: 'Sports',
    category: 'featured',
    description: 'Vibrant sports gradient',
    theme: {
      backgroundType: 'featured',
      backgroundColor: '#0a0a0a',
      backgroundImage: '/src/assets/chat_themes/sports-theme.png',
      sentBubbleColor: '#eab308',
      receivedBubbleColor: '#0891b2',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'yellow',
      sentTextColor: '#000000',
      receivedTextColor: '#cffafe',
    },
  },
  {
    id: 'featured-food-paradise',
    name: 'Food Paradise',
    category: 'featured',
    description: 'Pink-teal food theme',
    theme: {
      backgroundType: 'featured',
      backgroundColor: '#0a0a0a',
      backgroundImage: '/src/assets/chat_themes/food-theme.png',
      sentBubbleColor: '#ec4899',
      receivedBubbleColor: '#14b8a6',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'pink',
      sentTextColor: '#ffffff',
      receivedTextColor: '#f0fdfa',
    },
  },
  {
    id: 'featured-equations-gradient',
    name: 'Equation Pro',
    category: 'featured',
    description: 'Math gradient spectrum',
    theme: {
      backgroundType: 'featured',
      backgroundColor: '#0a0a0a',
      backgroundImage: '/src/assets/chat_themes/equations-theme.png',
      sentBubbleColor: '#22d3ee',
      receivedBubbleColor: '#a855f7',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'cyan',
      sentTextColor: '#083344',
      receivedTextColor: '#ffffff',
    },
  },
  {
    id: 'featured-tech-rainbow',
    name: 'Tech Rainbow',
    category: 'featured',
    description: 'Full spectrum tech',
    theme: {
      backgroundType: 'featured',
      backgroundColor: '#0a0a0a',
      backgroundImage: '/src/assets/chat_themes/tech-0-theme.png',
      sentBubbleColor: '#f472b6',
      receivedBubbleColor: '#06b6d4',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'pink',
      sentTextColor: '#ffffff',
      receivedTextColor: '#cffafe',
    },
  },
  {
    id: 'featured-midnight-elegance',
    name: 'Midnight',
    category: 'featured',
    description: 'Elegant black theme',
    theme: {
      backgroundType: 'solid',
      backgroundColor: '#000000',
      sentBubbleColor: '#8b5cf6',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'purple',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'featured-ocean-depths',
    name: 'Ocean Depths',
    category: 'featured',
    description: 'Deep blue gradient',
    theme: {
      backgroundType: 'solid',
      backgroundColor: '#0a0a0a',
      sentBubbleColor: '#3b82f6',
      receivedBubbleColor: '#1e293b',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'blue',
      sentTextColor: '#ffffff',
      receivedTextColor: '#cbd5e1',
    },
  },
  {
    id: 'featured-rose-gold-premium',
    name: 'Rose Gold',
    category: 'featured',
    description: 'Premium rose gold',
    theme: {
      backgroundType: 'solid',
      backgroundColor: '#0a0a0a',
      sentBubbleColor: '#f43f5e',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'pink',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'sunset-fire',
    name: 'Sunset Fire',
    category: 'featured',
    description: 'Warm sunset',
    theme: {
      backgroundType: 'solid',
      backgroundColor: '#0a0a0a',
      sentBubbleColor: '#f97316',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'orange',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'mint-breeze',
    name: 'Mint Breeze',
    category: 'featured',
    description: 'Fresh mint',
    theme: {
      backgroundType: 'solid',
      backgroundColor: '#0a0a0a',
      sentBubbleColor: '#10b981',
      receivedBubbleColor: '#1f2937',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'green',
      sentTextColor: '#ffffff',
      receivedTextColor: '#d1d5db',
    },
  },
  {
    id: 'pink-passion',
    name: 'Pink Passion',
    category: 'featured',
    description: 'Vibrant pink',
    theme: {
      backgroundType: 'solid',
      backgroundColor: '#0a0a0a',
      sentBubbleColor: '#ec4899',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'pink',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'royal-gold',
    name: 'Royal Gold',
    category: 'featured',
    description: 'Luxurious gold',
    theme: {
      backgroundType: 'solid',
      backgroundColor: '#0a0a0a',
      sentBubbleColor: '#f59e0b',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'yellow',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e5e5e5',
    },
  },

  // ============ SOLID THEMES ============
  {
    id: 'classic-dark',
    name: 'Classic Dark',
    category: 'solid',
    description: 'Clean purple bubbles',
    theme: {
      backgroundType: 'solid',
      backgroundColor: '#000000',
      sentBubbleColor: '#7c3aed',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'purple',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'midnight-blue',
    name: 'Midnight Blue',
    category: 'solid',
    description: 'Deep blue theme',
    theme: {
      backgroundType: 'solid',
      backgroundColor: '#0f172a',
      sentBubbleColor: '#3b82f6',
      receivedBubbleColor: '#1e293b',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'blue',
      sentTextColor: '#ffffff',
      receivedTextColor: '#cbd5e1',
    },
  },
  {
    id: 'forest-green',
    name: 'Forest Green',
    category: 'solid',
    description: 'Natural green',
    theme: {
      backgroundType: 'solid',
      backgroundColor: '#0a1f0a',
      sentBubbleColor: '#10b981',
      receivedBubbleColor: '#1f2937',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'green',
      sentTextColor: '#ffffff',
      receivedTextColor: '#d1d5db',
    },
  },
  {
    id: 'crimson-red',
    name: 'Crimson Red',
    category: 'solid',
    description: 'Bold red bubbles',
    theme: {
      backgroundType: 'solid',
      backgroundColor: '#0a0a0a',
      sentBubbleColor: '#dc2626',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'red',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'amber-gold',
    name: 'Amber Gold',
    category: 'solid',
    description: 'Warm amber',
    theme: {
      backgroundType: 'solid',
      backgroundColor: '#0a0a0a',
      sentBubbleColor: '#f59e0b',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'orange',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'pink-rose',
    name: 'Pink Rose',
    category: 'solid',
    description: 'Soft pink',
    theme: {
      backgroundType: 'solid',
      backgroundColor: '#0a0a0a',
      sentBubbleColor: '#ec4899',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'pink',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'cyan-aqua',
    name: 'Cyan Aqua',
    category: 'solid',
    description: 'Bright cyan',
    theme: {
      backgroundType: 'solid',
      backgroundColor: '#0a0a0a',
      sentBubbleColor: '#06b6d4',
      receivedBubbleColor: '#1e293b',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'cyan',
      sentTextColor: '#ffffff',
      receivedTextColor: '#cbd5e1',
    },
  },
  {
    id: 'indigo-deep',
    name: 'Indigo',
    category: 'solid',
    description: 'Deep indigo',
    theme: {
      backgroundType: 'solid',
      backgroundColor: '#0f0a1a',
      sentBubbleColor: '#6366f1',
      receivedBubbleColor: '#1e1b4b',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'indigo',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e0e7ff',
    },
  },
  {
    id: 'emerald-bright',
    name: 'Emerald',
    category: 'solid',
    description: 'Vibrant green',
    theme: {
      backgroundType: 'solid',
      backgroundColor: '#0a0a0a',
      sentBubbleColor: '#10b981',
      receivedBubbleColor: '#1f2937',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'green',
      sentTextColor: '#ffffff',
      receivedTextColor: '#d1d5db',
    },
  },
  {
    id: 'slate-gray',
    name: 'Slate',
    category: 'solid',
    description: 'Neutral slate',
    theme: {
      backgroundType: 'solid',
      backgroundColor: '#0f172a',
      sentBubbleColor: '#475569',
      receivedBubbleColor: '#1e293b',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'gray',
      sentTextColor: '#ffffff',
      receivedTextColor: '#cbd5e1',
    },
  },
  {
    id: 'lime-green',
    name: 'Lime',
    category: 'solid',
    description: 'Fresh lime',
    theme: {
      backgroundType: 'solid',
      backgroundColor: '#0a0a0a',
      sentBubbleColor: '#84cc16',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'green',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'orange-sunset',
    name: 'Orange',
    category: 'solid',
    description: 'Warm orange',
    theme: {
      backgroundType: 'solid',
      backgroundColor: '#0a0a0a',
      sentBubbleColor: '#f97316',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'orange',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'teal-ocean',
    name: 'Teal',
    category: 'solid',
    description: 'Deep teal',
    theme: {
      backgroundType: 'solid',
      backgroundColor: '#0a1419',
      sentBubbleColor: '#14b8a6',
      receivedBubbleColor: '#1e293b',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'cyan',
      sentTextColor: '#ffffff',
      receivedTextColor: '#cbd5e1',
    },
  },
  {
    id: 'violet-purple',
    name: 'Violet',
    category: 'solid',
    description: 'Rich violet',
    theme: {
      backgroundType: 'solid',
      backgroundColor: '#0a0a0a',
      sentBubbleColor: '#8b5cf6',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'purple',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'fuchsia-magenta',
    name: 'Fuchsia',
    category: 'solid',
    description: 'Bold fuchsia',
    theme: {
      backgroundType: 'solid',
      backgroundColor: '#0a0a0a',
      sentBubbleColor: '#d946ef',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'pink',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'sky-blue',
    name: 'Sky Blue',
    category: 'solid',
    description: 'Light blue',
    theme: {
      backgroundType: 'solid',
      backgroundColor: '#0a0f1a',
      sentBubbleColor: '#0ea5e9',
      receivedBubbleColor: '#1e293b',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'blue',
      sentTextColor: '#ffffff',
      receivedTextColor: '#cbd5e1',
    },
  },

  // ============ GRADIENT BACKGROUNDS ============
  {
    id: 'deep-space',
    name: 'Deep Space',
    category: 'gradient',
    description: 'Dark space gradient',
    theme: {
      backgroundType: 'gradient',
      backgroundColor: '#0a0a0a',
      backgroundColor2: '#1a1a2e',
      sentBubbleColor: '#8b5cf6',
      receivedBubbleColor: '#27272a',
      sentBubbleGradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'purple',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'ocean-depths',
    name: 'Ocean Depths',
    category: 'gradient',
    description: 'Deep blue gradient',
    theme: {
      backgroundType: 'gradient',
      backgroundColor: '#0f172a',
      backgroundColor2: '#1e293b',
      sentBubbleColor: '#3b82f6',
      receivedBubbleColor: '#334155',
      sentBubbleGradient: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'blue',
      sentTextColor: '#ffffff',
      receivedTextColor: '#cbd5e1',
    },
  },
  {
    id: 'purple-haze',
    name: 'Purple Haze',
    category: 'gradient',
    description: 'Purple gradient background',
    theme: {
      backgroundType: 'gradient',
      backgroundColor: '#1a0a1a',
      backgroundColor2: '#2d1b4e',
      sentBubbleColor: '#a855f7',
      receivedBubbleColor: '#3a2a5a',
      sentBubbleGradient: 'linear-gradient(135deg, #a855f7 0%, #8b5cf6 100%)',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'purple',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e9d5ff',
    },
  },
  {
    id: 'fire-ember',
    name: 'Fire Ember',
    category: 'gradient',
    description: 'Red to orange fire',
    theme: {
      backgroundType: 'gradient',
      backgroundColor: '#1a0505',
      backgroundColor2: '#2e0a0a',
      sentBubbleColor: '#ef4444',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'red',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'tropical-paradise',
    name: 'Tropical',
    category: 'gradient',
    description: 'Cyan to green',
    theme: {
      backgroundType: 'gradient',
      backgroundColor: '#051410',
      backgroundColor2: '#0a1a1e',
      sentBubbleColor: '#14b8a6',
      receivedBubbleColor: '#1e293b',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'cyan',
      sentTextColor: '#ffffff',
      receivedTextColor: '#cbd5e1',
    },
  },
  {
    id: 'lavender-mist',
    name: 'Lavender',
    category: 'gradient',
    description: 'Soft purple',
    theme: {
      backgroundType: 'gradient',
      backgroundColor: '#0f0a1a',
      backgroundColor2: '#1a0f2e',
      sentBubbleColor: '#a78bfa',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'purple',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'peach-cream',
    name: 'Peach',
    category: 'gradient',
    description: 'Warm peach',
    theme: {
      backgroundType: 'gradient',
      backgroundColor: '#1a0f0a',
      backgroundColor2: '#2e1a14',
      sentBubbleColor: '#fb923c',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'orange',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'mint-fresh',
    name: 'Mint',
    category: 'gradient',
    description: 'Fresh mint',
    theme: {
      backgroundType: 'gradient',
      backgroundColor: '#0a1410',
      backgroundColor2: '#0f1e1a',
      sentBubbleColor: '#34d399',
      receivedBubbleColor: '#1f2937',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'green',
      sentTextColor: '#ffffff',
      receivedTextColor: '#d1d5db',
    },
  },
  {
    id: 'royal-blue',
    name: 'Royal',
    category: 'gradient',
    description: 'Royal blue',
    theme: {
      backgroundType: 'gradient',
      backgroundColor: '#0a0f1a',
      backgroundColor2: '#0f1428',
      sentBubbleColor: '#3b82f6',
      receivedBubbleColor: '#1e293b',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'blue',
      sentTextColor: '#ffffff',
      receivedTextColor: '#cbd5e1',
    },
  },
  {
    id: 'rose-wine',
    name: 'Rose Wine',
    category: 'gradient',
    description: 'Deep rose',
    theme: {
      backgroundType: 'gradient',
      backgroundColor: '#1a0a0f',
      backgroundColor2: '#2e1420',
      sentBubbleColor: '#f43f5e',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'pink',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'amber-glow',
    name: 'Amber',
    category: 'gradient',
    description: 'Warm amber',
    theme: {
      backgroundType: 'gradient',
      backgroundColor: '#1a1008',
      backgroundColor2: '#2e1e0f',
      sentBubbleColor: '#f59e0b',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'orange',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'electric-blue',
    name: 'Electric',
    category: 'gradient',
    description: 'Bright electric',
    theme: {
      backgroundType: 'gradient',
      backgroundColor: '#0a0a1a',
      backgroundColor2: '#0f0f2e',
      sentBubbleColor: '#0ea5e9',
      receivedBubbleColor: '#1e293b',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'cyan',
      sentTextColor: '#ffffff',
      receivedTextColor: '#cbd5e1',
    },
  },

  // ============ ARTISTIC BACKGROUNDS (Dense Telegram-style patterns) ============
  {
    id: 'food-fiesta',
    name: 'Food Fiesta',
    category: 'artistic',
    description: 'Delicious food icons',
    theme: {
      backgroundType: 'artistic',
      backgroundColor: '#0a0a0a',
      backgroundPattern: 'Food Fiesta',
      sentBubbleColor: '#f59e0b',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'orange',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'floral-dreams',
    name: 'Floral Dreams',
    category: 'artistic',
    description: 'Beautiful flowers pattern',
    theme: {
      backgroundType: 'artistic',
      backgroundColor: '#0a0a0a',
      backgroundPattern: 'Floral Dreams',
      sentBubbleColor: '#ec4899',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'pink',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'cosmic-space',
    name: 'Cosmic Space',
    category: 'artistic',
    description: 'Space objects pattern',
    theme: {
      backgroundType: 'artistic',
      backgroundColor: '#0a0a1a',
      backgroundPattern: 'Cosmic Space',
      sentBubbleColor: '#8b5cf6',
      receivedBubbleColor: '#1e1b4b',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'purple',
      sentTextColor: '#ffffff',
      receivedTextColor: '#e0e7ff',
    },
  },
  {
    id: 'tech-gadgets',
    name: 'Tech Gadgets',
    category: 'artistic',
    description: 'Modern tech devices',
    theme: {
      backgroundType: 'artistic',
      backgroundColor: '#0a0a0a',
      backgroundPattern: 'Tech Gadgets',
      sentBubbleColor: '#06b6d4',
      receivedBubbleColor: '#1e293b',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'cyan',
      sentTextColor: '#ffffff',
      receivedTextColor: '#cbd5e1',
    },
  },
  {
    id: 'winter-frost',
    name: 'Winter Frost',
    category: 'artistic',
    description: 'Snowflakes pattern',
    theme: {
      backgroundType: 'artistic',
      backgroundColor: '#0a0a14',
      backgroundPattern: 'Winter Frost',
      sentBubbleColor: '#60a5fa',
      receivedBubbleColor: '#1e293b',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'blue',
      sentTextColor: '#ffffff',
      receivedTextColor: '#cbd5e1',
    },
  },

  // ============ MORE ARTISTIC THEMES (from artisticPatterns.ts) ============
  {
    id: 'cosmic-nebula',
    name: 'Cosmic Nebula',
    category: 'artistic',
    description: 'Purple space nebula',
    theme: {
      backgroundType: 'artistic',
      backgroundColor: '#0a0a1a',
      backgroundPattern: 'Cosmic Nebula',
      sentBubbleColor: '#8b5cf6',
      receivedBubbleColor: '#1e1b4b',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'purple',
      sentTextColor: '#f3e8ff',
      receivedTextColor: '#e0e7ff',
    },
  },
  {
    id: 'aurora-dreams',
    name: 'Aurora Dreams',
    category: 'artistic',
    description: 'Northern lights effect',
    theme: {
      backgroundType: 'artistic',
      backgroundColor: '#0a1628',
      backgroundPattern: 'Aurora Dreams',
      sentBubbleColor: '#06b6d4',
      receivedBubbleColor: '#0f172a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'cyan',
      sentTextColor: '#cffafe',
      receivedTextColor: '#cbd5e1',
    },
  },
  {
    id: 'deep-ocean',
    name: 'Deep Ocean',
    category: 'artistic',
    description: 'Ocean depths',
    theme: {
      backgroundType: 'artistic',
      backgroundColor: '#020d1a',
      backgroundPattern: 'Deep Ocean',
      sentBubbleColor: '#3b82f6',
      receivedBubbleColor: '#1e293b',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'blue',
      sentTextColor: '#dbeafe',
      receivedTextColor: '#cbd5e1',
    },
  },
  {
    id: 'violet-sunset',
    name: 'Violet Sunset',
    category: 'artistic',
    description: 'Purple sunset glow',
    theme: {
      backgroundType: 'artistic',
      backgroundColor: '#1a0a0f',
      backgroundPattern: 'Violet Sunset',
      sentBubbleColor: '#a855f7',
      receivedBubbleColor: '#2d1b4e',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'purple',
      sentTextColor: '#f3e8ff',
      receivedTextColor: '#e9d5ff',
    },
  },
  {
    id: 'emerald-forest',
    name: 'Emerald Forest',
    category: 'artistic',
    description: 'Forest greens',
    theme: {
      backgroundType: 'artistic',
      backgroundColor: '#051a0a',
      backgroundPattern: 'Emerald Forest',
      sentBubbleColor: '#059669',
      receivedBubbleColor: '#1f2937',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'green',
      sentTextColor: '#d1fae5',
      receivedTextColor: '#d1d5db',
    },
  },
  {
    id: 'crimson-night',
    name: 'Crimson Night',
    category: 'artistic',
    description: 'Deep red atmosphere',
    theme: {
      backgroundType: 'artistic',
      backgroundColor: '#1a0505',
      backgroundPattern: 'Crimson Night',
      sentBubbleColor: '#dc2626',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'red',
      sentTextColor: '#fee2e2',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    category: 'artistic',
    description: 'Warm golden tones',
    theme: {
      backgroundType: 'artistic',
      backgroundColor: '#1a1508',
      backgroundPattern: 'Golden Hour',
      sentBubbleColor: '#d97706',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'orange',
      sentTextColor: '#fef3c7',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'glacial-ice',
    name: 'Glacial Ice',
    category: 'artistic',
    description: 'Icy blue atmosphere',
    theme: {
      backgroundType: 'artistic',
      backgroundColor: '#0a1419',
      backgroundPattern: 'Glacial Ice',
      sentBubbleColor: '#60a5fa',
      receivedBubbleColor: '#1e293b',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'blue',
      sentTextColor: '#dbeafe',
      receivedTextColor: '#cbd5e1',
    },
  },
  {
    id: 'purple-haze',
    name: 'Purple Haze',
    category: 'artistic',
    description: 'Hazy purple mist',
    theme: {
      backgroundType: 'artistic',
      backgroundColor: '#0f0a1a',
      backgroundPattern: 'Purple Haze',
      sentBubbleColor: '#7c3aed',
      receivedBubbleColor: '#3a2a5a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'purple',
      sentTextColor: '#e9d5ff',
      receivedTextColor: '#e9d5ff',
    },
  },
  {
    id: 'mystical-forest',
    name: 'Mystical Forest',
    category: 'artistic',
    description: 'Enchanted forest',
    theme: {
      backgroundType: 'artistic',
      backgroundColor: '#051410',
      backgroundPattern: 'Mystical Forest',
      sentBubbleColor: '#10b981',
      receivedBubbleColor: '#1f2937',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'green',
      sentTextColor: '#d1fae5',
      receivedTextColor: '#d1d5db',
    },
  },
  {
    id: 'electric-storm',
    name: 'Electric Storm',
    category: 'artistic',
    description: 'Lightning storm',
    theme: {
      backgroundType: 'artistic',
      backgroundColor: '#0a0a1a',
      backgroundPattern: 'Electric Storm',
      sentBubbleColor: '#0891b2',
      receivedBubbleColor: '#0f172a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'cyan',
      sentTextColor: '#cffafe',
      receivedTextColor: '#cbd5e1',
    },
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold',
    category: 'artistic',
    description: 'Rose gold elegance',
    theme: {
      backgroundType: 'artistic',
      backgroundColor: '#1a0f0f',
      backgroundPattern: 'Rose Gold',
      sentBubbleColor: '#be185d',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 14,
      accentColor: 'pink',
      sentTextColor: '#fce7f3',
      receivedTextColor: '#e5e5e5',
    },
  },

  // ============ PATTERN THEMES (from patternBackgrounds.ts) ============
  {
    id: 'hexagon-grid',
    name: 'Hexagon Grid',
    category: 'pattern',
    description: 'Geometric hexagons',
    theme: {
      backgroundType: 'pattern',
      backgroundColor: '#0a0a0a',
      backgroundPattern: 'hexagon-grid',
      sentBubbleColor: '#7c3aed',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'purple',
      sentTextColor: '#e9d5ff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'diamond-tiles',
    name: 'Diamond Tiles',
    category: 'pattern',
    description: 'Diamond shaped tiles',
    theme: {
      backgroundType: 'pattern',
      backgroundColor: '#0a0a0a',
      backgroundPattern: 'diamond-tiles',
      sentBubbleColor: '#8b5cf6',
      receivedBubbleColor: '#1f1f1f',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'purple',
      sentTextColor: '#f3e8ff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'zigzag',
    name: 'Zigzag Pattern',
    category: 'pattern',
    description: 'Zigzag lines',
    theme: {
      backgroundType: 'pattern',
      backgroundColor: '#0a0a0a',
      backgroundPattern: 'zigzag',
      sentBubbleColor: '#a855f7',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'purple',
      sentTextColor: '#f3e8ff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'dots-matrix',
    name: 'Dots Matrix',
    category: 'pattern',
    description: 'Dot grid pattern',
    theme: {
      backgroundType: 'pattern',
      backgroundColor: '#0a0a0a',
      backgroundPattern: 'dots-matrix',
      sentBubbleColor: '#7c3aed',
      receivedBubbleColor: '#1f1f1f',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'purple',
      sentTextColor: '#e9d5ff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'cross-hatch',
    name: 'Cross Hatch',
    category: 'pattern',
    description: 'Cross hatch grid',
    theme: {
      backgroundType: 'pattern',
      backgroundColor: '#0a0a0a',
      backgroundPattern: 'cross-hatch',
      sentBubbleColor: '#6b21a8',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'purple',
      sentTextColor: '#e9d5ff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'waves',
    name: 'Waves',
    category: 'pattern',
    description: 'Wave pattern',
    theme: {
      backgroundType: 'pattern',
      backgroundColor: '#0a0a0a',
      backgroundPattern: 'waves',
      sentBubbleColor: '#3b82f6',
      receivedBubbleColor: '#1e293b',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'blue',
      sentTextColor: '#dbeafe',
      receivedTextColor: '#cbd5e1',
    },
  },
  {
    id: 'checkerboard',
    name: 'Checkerboard',
    category: 'pattern',
    description: 'Classic checkerboard',
    theme: {
      backgroundType: 'pattern',
      backgroundColor: '#0a0a0a',
      backgroundPattern: 'checkerboard',
      sentBubbleColor: '#8b5cf6',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'purple',
      sentTextColor: '#f3e8ff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'diagonal-lines',
    name: 'Diagonal Lines',
    category: 'pattern',
    description: 'Diagonal stripes',
    theme: {
      backgroundType: 'pattern',
      backgroundColor: '#0a0a0a',
      backgroundPattern: 'diagonal-lines',
      sentBubbleColor: '#7c3aed',
      receivedBubbleColor: '#1f1f1f',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'purple',
      sentTextColor: '#e9d5ff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'triangles',
    name: 'Triangles',
    category: 'pattern',
    description: 'Triangle pattern',
    theme: {
      backgroundType: 'pattern',
      backgroundColor: '#0a0a0a',
      backgroundPattern: 'triangles',
      sentBubbleColor: '#a855f7',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'purple',
      sentTextColor: '#f3e8ff',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'brick-wall',
    name: 'Brick Wall',
    category: 'pattern',
    description: 'Brick wall pattern',
    theme: {
      backgroundType: 'pattern',
      backgroundColor: '#0a0a0a',
      backgroundPattern: 'brick-wall',
      sentBubbleColor: '#d97706',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'orange',
      sentTextColor: '#fef3c7',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'weave',
    name: 'Weave',
    category: 'pattern',
    description: 'Weave pattern',
    theme: {
      backgroundType: 'pattern',
      backgroundColor: '#0a0a0a',
      backgroundPattern: 'weave',
      sentBubbleColor: '#059669',
      receivedBubbleColor: '#1f2937',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'green',
      sentTextColor: '#d1fae5',
      receivedTextColor: '#d1d5db',
    },
  },
  {
    id: 'plus-signs',
    name: 'Plus Signs',
    category: 'pattern',
    description: 'Plus sign grid',
    theme: {
      backgroundType: 'pattern',
      backgroundColor: '#0a0a0a',
      backgroundPattern: 'plus-signs',
      sentBubbleColor: '#0891b2',
      receivedBubbleColor: '#334155',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'cyan',
      sentTextColor: '#cffafe',
      receivedTextColor: '#cbd5e1',
    },
  },
  {
    id: 'polka-dots',
    name: 'Polka Dots',
    category: 'pattern',
    description: 'Polka dot pattern',
    theme: {
      backgroundType: 'pattern',
      backgroundColor: '#0a0a0a',
      backgroundPattern: 'polka-dots',
      sentBubbleColor: '#ec4899',
      receivedBubbleColor: '#27272a',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'pink',
      sentTextColor: '#fce7f3',
      receivedTextColor: '#e5e5e5',
    },
  },
  {
    id: 'squares-grid',
    name: 'Squares Grid',
    category: 'pattern',
    description: 'Square grid pattern',
    theme: {
      backgroundType: 'pattern',
      backgroundColor: '#111827',
      backgroundPattern: 'squares-grid',
      sentBubbleColor: '#4f46e5',
      receivedBubbleColor: '#1e293b',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'indigo',
      sentTextColor: '#e0e7ff',
      receivedTextColor: '#cbd5e1',
    },
  },
  {
    id: 'argyle',
    name: 'Argyle',
    category: 'pattern',
    description: 'Argyle pattern',
    theme: {
      backgroundType: 'pattern',
      backgroundColor: '#0a0a0a',
      backgroundPattern: 'argyle',
      sentBubbleColor: '#10b981',
      receivedBubbleColor: '#1f2937',
      bubbleShapePreset: 'pill',
      bubbleBorderRadius: 12,
      accentColor: 'green',
      sentTextColor: '#d1fae5',
      receivedTextColor: '#d1d5db',
    },
  },
];

export function getThemePreset(id: string): ThemePreset | undefined {
  return themePresets.find(p => p.id === id);
}

export function getThemesByCategory(category: ThemePreset['category']): ThemePreset[] {
  return themePresets.filter(p => p.category === category);
}
